# version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: mariadb
            MYSQL_USER: gigiri
            MYSQL_PASSWORD: 1234
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_network
        restart: always

    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/html
            # - ./requirements/nginx/conf:/etc/nginx/conf.d
        networks:
            - inception_network
        depends_on:
            - wordpress
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        # image: wordpress:42
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_USER: gigiri
            WORDPRESS_DB_PASSWORD: 4321
            WORDPRESS_DB_NAME: mariadb
        ports:
            - "9000:9000"
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception_network
        depends_on:
            - mariadb

volumes:
    mariadb_data:
    nginx_conf:
    wordpress_data:

networks:
  inception_network:
    # driver: bridge
